services:
  
  server:
   build: ./app
   ports:
     - 8004:8000
   command: uvicorn main:app --host 0.0.0.0 --reload
   volumes:
     - ./app:/src/app
   environment:
     - CELERY_BROKER_URL=redis://redis:6379/0
     - CELERY_RESULT_BACKEND=redis://redis:6379/0
   depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_started
  
  celery_worker:
   build: ./app
   command: celery --app=worker.celery worker --loglevel=INFO --logfile=logs/celery.log
   volumes:
     - ./app:/src/app
   environment:
     - CELERY_BROKER_URL=redis://redis:6379/0
     - CELERY_RESULT_BACKEND=redis://redis:6379/0
   depends_on:
     - server
     - redis
  
  redis:
    image: redis:7.0-alpine3.15

  db:
    image: postgres:14-alpine3.15
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dataset
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres && psql --username=postgres --list"]
      interval: 5s
      timeout: 5s
      retries: 5